import React from "react";
import ExperienceCard from "./Components/ExperienceCard";
import SkillsCard from "./Components/SkillCard";
import CertificationCard from "./Components/CertificationCard";

const experiences = [
  {
    image: "/images/image 2.png",
    role: "Software Developer",
    company: "Stealth",
    duration: "Jan 2024-Present",
    location: "Remote",
    description:
      "Created a multi-track streaming platform for a virtual conference with chat integration, a rating system, and a sidebar that displays & updates the sessions in real-time according to the user's time zone. Designed & developed an interactive game commemorating 20 years of the Spring Framework. The microsite was used to market VMware's SpringOne conference. All pixel art was meticulously crafted by hand.",
  },
  {
    image: "/images/image 2-1.png",
    role: "Software Developer",
    company: "Stealth",
    duration: "Jan 2024-Present",
    location: "Remote",
    description:
      "Created a multi-track streaming platform for a virtual conference with chat integration, a rating system, and a sidebar that displays & updates the sessions in real-time according to the user's time zone. Designed & developed an interactive game commemorating 20 years of the Spring Framework. The microsite was used to market VMware's SpringOne conference. All pixel art was meticulously crafted by hand.",
  },
  {
    image: "/images/image 2-2.png",
    role: "Software Developer",
    company: "Stealth",
    duration: "Jan 2024-Present",
    location: "Remote",
    description:
      "Created a multi-track streaming platform for a virtual conference with chat integration, a rating system, and a sidebar that displays & updates the sessions in real-time according to the user's time zone. Designed & developed an interactive game commemorating 20 years of the Spring Framework. The microsite was used to market VMware's SpringOne conference. All pixel art was meticulously crafted by hand.",
  },
  {
    image: "/images/image 2-3.png",
    role: "Software Developer",
    company: "Stealth",
    duration: "Jan 2024-Present",
    location: "Remote",
    description:
      "Created a multi-track streaming platform for a virtual conference with chat integration, a rating system, and a sidebar that displays & updates the sessions in real-time according to the user's time zone. Designed & developed an interactive game commemorating 20 years of the Spring Framework. The microsite was used to market VMware's SpringOne conference. All pixel art was meticulously crafted by hand.",
  },
];

const skills = [
  {
    title: "Programming Languages",
    skills: [
      "C++ (Data Structures and Algorithms)",
      "JavaScript (ES6+)",
      "TypeScript",
      "Python",
      "Dart",
      "SQL",
    ],
  },
  {
    title: "Frontend",
    skills: [
      "React.js (Hooks, Context API, Recoil)",
      "Next.js",
      "Flutter (Provider, GetX)",
      "CSS (Flexbox, Tailwind CSS)",
      "HTML5",
      "Custom Hooks",
    ],
  },
  {
    title: "Backend",
    skills: [
      "Node.js (Express.js, Koa.js)",
      "RESTful API Development",
      "gRPC",
      "WebSockets",
      "Authentication (NextAuth, OAuth)",
      "Serverless Architecture (AWS Lambda, Firebase Functions)",
      "Message Queues (RabbitMQ, Kafka)",
      "Real-Time Communication (WebRTC)",
      "Advanced System Design (Load Balancers, Proxies, Rate Limiting, Scaling)",
    ],
  },
  {
    title: "Databases",
    skills: [
      "MongoDB",
      "PostgreSQL",
      "Firebase (Firestore, Realtime DB)",
      "Redis (Deep Dive)",
      "Database Design (Indexing, Normalization, Sharding, Replication)",
    ],
  },
  {
    title: "Cloud Platforms",
    skills: [
      "AWS (EC2, S3, Lambda, EKS, CDNs, Load Balancers)",
      "Google Cloud Platform",
      "Newer Clouds (Fly.io, Remix)",
    ],
  },
  {
    title: "DevOps",
    skills: [
      "Container Orchestration (Docker Swarm, Kubernetes)",
      "CI/CD (Continuous Integration/Continuous Deployment)",
      "Serverless Deployments (AWS Lambda, Serverless Framework)",
      "Monitoring Systems (Prometheus, Grafana, New Relic)",
    ],
  },
  {
    title: "Tools",
    skills: [
      "Docker (Containerization, Docker Swarm, Kubernetes)",
      "CI/CD Pipelines (Jenkins, GitLab CI)",
      "Prometheus & Grafana (Monitoring)",
      "New Relic (APM)",
      "Nginx (Reverse Proxies)",
      "Git (Version Control)",
      "npm/yarn (Package Management)",
      "Autogenerated Clients (Swagger)",
    ],
  },
  {
    title: "Design",
    skills: [
      "Figma",
      "Adobe Photoshop",
      "Adobe Illustrator",
      "Adobe Premiere Pro",
      "Adobe After Effects",
      "Adobe Media Encoder",
      "Blender",
      "DaVinci Resolve",
    ],
  },
  {
    title: "Frameworks",
    skills: [
      "React.js",
      "Next.js",
      "Express.js",
      "Flutter",
      "Spring Boot",
      "Django",
      "ASP.NET Core",
    ],
  },
];

const certifications = [
  {
    image: "/images/placeholder.png",
    title: "AWS Academy Graduate - AWS Academy Cloud Foundations",
    dateIssued: "Jan 2024",
  },
  {
    image: "/images/placeholder.png",
    title: "Cybersecurity Essentials",
    dateIssued: "Jun 2023",
  },
  {
    image: "/images/placeholder.png",
    title: "DevNet Associate",
    dateIssued: "Jun 2023",
  },
  {
    image: "/images/placeholder.png",
    title: "Goldman Sachs Software Engineering Virtual Experience Program",
    dateIssued: "Jun 2023",
  },
];

const ExperienceSection: React.FC = () => {
  return (
    <div className="container mx-auto py-12 px-4 sm:px-6 lg:px-8">
      <div className="mb-12">
        <h2 className="text-3xl font-extrabold text-gray-900 sm:text-4xl text-center mb-8 tracking-tightest pt-8 pb-8">
          Experience
        </h2>
        <div className="grid grid-cols-1 gap-8">
          {experiences.map((experience, index) => (
            <div key={index} className="col-span-1 md:col-span-2">
              <ExperienceCard
                image={experience.image}
                role={experience.role}
                company={experience.company}
                duration={experience.duration}
                location={experience.location}
                description={experience.description}
              />
            </div>
          ))}
        </div>
      </div>
      <div className="mb-12">
        <h2 className="text-3xl font-extrabold text-gray-900 sm:text-4xl text-center mb-8 tracking-tightest">
          Skills
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8">
          {skills.map((skillSet, index) => (
            <SkillsCard
              key={index}
              title={skillSet.title}
              skills={skillSet.skills}
            />
          ))}
        </div>
      </div>
      <div>
        <h2 className="text-3xl font-extrabold text-gray-900 sm:text-4xl text-center mb-8 tracking-tightest">
          Certifications
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-8">
          {certifications.map((certification, index) => (
            <CertificationCard
              key={index}
              image={certification.image}
              title={certification.title}
              dateIssued={certification.dateIssued}
            />
          ))}
        </div>
      </div>
    </div>
  );
};

export default ExperienceSection;
